

gui = StandardGUI(sim, [50, 50, 700, 500], 0.05, ...
  [0.0, 1/3, 1.0, 2/3], [1, 1], 0.1, ...
  [0.0, 0.0, 1.0, 1/3], [6, 3]);

gui.addVisualization(MultiPlot({'field u', 'field u', 'stim B'}, ...
  {'activation', 'output', 'output'}, [1, 30, 1], 'horizontal', ...
  {'YLim', [-10,100], 'Box', 'on'}, ...
  {{'b', 'LineWidth', 2}, {'r'}, {'g'}, {'g'}}, ...
  'field u', 'field position', 'activation/ouput/input'), ...
  [1, 1]);

gui.addControl(ParameterSlider('h', 'field u', 'h', [-10, 0],...
  '%0.1f', 1, 'resting level of field u'), [1, 1]);


gui.addControl(ParameterSlider('c_exc', 'u -> u', 'amplitudeExc', [0, 40], '%0.1f', 1, ...
  'strength of lateral excitation'), [2, 1]);
gui.addControl(ParameterSlider('c_inh', 'u -> u', 'amplitudeInh', [0, 40], '%0.1f', 1, ...
  'strength of lateral inhibition'), [2, 2]);
gui.addControl(ParameterSlider('v', 'u -> u', 'velocity', [0, 1000], '%0.1f', -1, ...
  'strength of CD signal'), [2, 3]);

gui.addControl(ParameterSlider('global', 'u -> u', 'amplitudeGlobal', [0, 5], '%0.1f', -1, ...
  'strength of CD signal'), [1, 2]);

gui.addControl(ParameterSlider('s2_sigma', 'stim B', 'sigma', [0, 100], '%0.1f', 1, ...
  'position of stimulus 1'), [4, 1]);
%gui.addControl(ParameterSlider('c_s2', 'stim B', 'amplitude', [0, 20], '%0.1f', 1, ...
%  'stength of stimulus 1'), [4, 2]);

gui.addControl(ParameterSlider('p_s2', 'stim B', 'position', [0, 200], '%0.1f', 1, ...
  'position of stimulus 2'), [5, 1]);
gui.addControl(ParameterSlider('c_s2', 'stim B', 'amplitude', [0, 16], '%0.1f', 1, ...
  'stength of stimulus 2'), [5, 2]);
gui.addControl(ParameterSlider('m', 'field u', 'm', [0, 100], '%0.1f', 1, ...
  'stength of stimulus 2'), [1, 3]);
gui.addVisualization(TimeDisplay(), [3, 2], [1, 1], 'control');
tMax = inf;

% initialize simulator and GUI
sim.init();
gui.init();
act=[];